### PR TITLE
Adding defaultWMSVersion on themesConfig.json file

### PR DESCRIPTION
**Pull request by mohammadamin46bd**
Adding defaultWMSVersion option on themesConfig.json file

### CODE REVIEW

**Comment by manisandro** [comment]
Please put some effort into meaningful commit messages and clean commits...

**Comment by manisandro** [comment]
Just for clarity, I will refuse to merge any pull request in which no effort was put to clean up and clarify the commits.

**Comment by mohammadamin46bd** [comment]
Can you specify for example what to clean up here for the last commit and last commit message?
Do you need all the commit message to change?

**Comment by manisandro** [comment]
The pull request currently contains 9 commits, of which the first five are unrelated to the actual PR and just add and remove code again, and the last two commits have the same message and just do whitespace changes.

A pull request should contain one commit per change, the changes done should be polished (i.e. no random whitespace changes) and contain just changes related to what is described in the pull request.

`git rebase -i` and `git commit --amend` are your friends here.

**Comment by mohammadamin46bd** [comment]
Ok, thanks for the clarification.

**Comment by manisandro** [comment]
Superseded by #43

**Pull request closed without merging**
