### PR TITLE
Swedish translations

### PR DESCRIPTION
**Pull request by igorti**

### CODE REVIEW

**Comment by manisandro** [comment]
Please place the translations to `qwc2/translations`. The idea is that all common translations are in the common qwc2 part, and only application specific extra translations or overridden translations are in the user specific app.

**Comment by igorti** [comment]
Sure! It seams like `qwc-demo-app` still relies on translation files being present in `qwc-demo-app/translations` folder?

**Comment by manisandro** [comment]
Yes, but it always updates them against the translations in the qwc2 module. The objective is to make it easier for people to rebase their application against the latest qwc2 module. Say if a common qwc2 component gets a new string, before users would have needed to manually merge the new translations, now it happens automatically. Still, users may have custom components not in qwc2 or may wish to override some translations, hence the final translations are still the ones of the application.

**Comment by igorti** [comment]
Right, now I get the idea, thanks! This PR can be closed, translations coming in `qwc2`.

**Pull request closed without merging**
