### PR TITLE
Local coordinate system support 3008

### PR DESCRIPTION
**Pull request by mohammadamin46bd**
Local coordinate system support 3008:
Sample themeConfig and config file for local coordinate system.
Added proj4 dependency.
Added projection definition for 3008 at appConfig.js file.

### CODE REVIEW

**Comment by manisandro** [comment]
This PR contains many user-specific configurations which do not belong in the generic example.

**Comment by manisandro** [comment]
I don't think there is any value adding `EPSG:3008` to the demo, it is again something user-specific. Also, why do you need to add proj in package.json?

**Comment by mohammadamin46bd** [comment]
Ok. Adding EPSG:3008 to appConfig.js is user-specifc and will remove that.

I was writting theme.json file with clean local coordinate system by using proj module. For example, by using it it looks like below on theme.json file for each leyer and map (for not making client to transform them on the fly from EPSG:4326 to local system(EPSG:3008)):
"bbox": {
"crs": "EPSG:3008","bounds": [170084.98447703285, 6182800.837815832, 207057.58128418546, 6236056.280983914]
},
"initialBbox": {"crs": "EPSG:3008","bounds": [170084.98447703285, 6182800.837815832, 207057.58128418546, 6236056.280983914]}
 {"name": "omrade", "title": "Område", "visibility": false, "queryable": true, "displayField": "maptip", "attribution": "C4-teknik", "attributionUrl": "http://www.kristianstad.se", "abstract": "Områden för parkindelningen. Objektnummer.", "dataUrl": "https://www.kristianstad.se/sv/uppleva-och-gora/idrott-motion-bad-och-friluftsliv/friluftsliv-och-motion/parker-och-gronomraden/", "opacity": 255, "keywords": "park,område,indelning",
"bbox": {"crs": "EPSG:3008","bounds": [173888.5595443413, 6182820.0642549535, 207057.87868444252, 6236034.012831945]}}

But this might be user-specific and will remove it.

**Comment by mohammadamin46bd** [comment]
Closing this request as it is user-specific.

**Pull request closed without merging**
